### ISSUE TITLE
Indicate area return unit

### ISSUE THREAD

**Issue by deeplook** [omanges/turfpy#30]
I see that `measurements.length` says something about the return value (default km), but `measurements.area` doesn't. This an be easily fixed, but it would be perhaps more helpful to allow for different langth and area units. There are some packages for handling units in a way that they can be used in calculations, but these are likely not enough standardized...

**Comment by omanges** [comment]
Addressed in https://github.com/omanges/turfpy/commit/9deea11ac647169cd0ac0fbef26b6dd2ab494351#diff-bd9667bdd2aeaebd63dcc2dc03e5f622
