### ISSUE TITLE
Add new functionality: lineIntersect()

### ISSUE THREAD

**Issue by kapitan-iglu** [omanges/turfpy#66]
I'm missing this function: [lineIntersect()](https://turfjs.org/docs/#lineIntersect). Is it possible to add it?

**Comment by omanges** [comment]
@kapitan-iglu have you had some progress on this or should I start with this?

**Comment by kapitan-iglu** [comment]
No progress, I'm not familiar with this lib enough to add features by my self. Feel free to start.

**Comment by omanges** [comment]
@kapitan-iglu  I have added the` line intersect` feature but for using it geopandas and (pygeos or tree) are needed to be installed as dependency give it a try 😉
