### ISSUE TITLE
Add support for turf.sector

### ISSUE THREAD

**Issue by martimpassos** [omanges/turfpy#98]
I'm currently using shapely + pyproj to draw circular sectors (viewcones for geolocated images), which takes an awful long time since I have to reproject every vertex when building each of my 4k polygons. Are you planning to include this method in turfpy?

![image](https://user-images.githubusercontent.com/49573683/121542703-bca84880-c9de-11eb-985d-30c87ff406c0.png)

**Comment by omanges** [comment]
@martimpassos yes we will take this feature in the upcoming release.

**Comment by martimpassos** [comment]
amazing news!

**Comment by omanges** [comment]
@martimpassos  Added in the new release v0.0.7 also checkout line-arc function
